flowchart LR
    A[Step 1 <br> P<SUB>1</SUB>=0.95] --> B
    B[Step 2 <br> P<SUB>2</SUB>=0.95] --> C
    C[Step 3 <br> P<SUB>3</SUB>=0.95] --> D
    D[Step 4 <br> P<SUB>4</SUB>=0.95] --> E
    E[Step 5 <br> P<SUB>5</SUB>=0.95]