project:
  type: book
  output-dir: docs

book:
  chapters:
    - index.qmd
    - chapter000_BasicConcepts.qmd
    - chapter001_Distributions.qmd
    - references.qmd
  downloads: [pdf]
    
format:
  html:
    include-in-header: mathjax.html
    theme: cosmo
  pdf:
    documentclass: scrbook
    papersize: A4
    number-sections: true
    toc: true
    lof: true
    lot: true
    fig-align: center
    fig-pos: 'ht'
    fig-format: pdf


