project:
  type: book
  output-dir: docs

book:
  chapters:
    - index.qmd
    - chapter000_BasicConcepts.qmd
    - chapter001_Distributions.qmd
    - SamplingMethods.qmd
    - chapter002_InferentialStatistics.qmd
    - chapter003_Regression.qmd
    - chapter004_ProductionStatistics.qmd
    - chapter005_DoE.qmd
    - references.qmd
  downloads: [pdf]
    
format:
  html:
    include-in-header: mathjax.html
    theme: cosmo
    fig-width: 8
    fig-height: 5
    fig-format: png
  titlepage-pdf:
    include-in-header: tex/preamble.tex
    documentclass: scrbook
    coverpage-include-file:
      - tex/copyright.tex
    titlepage-include-file:
      - tex/dedication.tex
    coverpage: true
    coverpage-bg-image: "img/cover.jpg"
    coverpage-author: "T. A. Weber"
    coverpage-header: "Applied AI for Digital Production Management"
    coverpage-footer: "Deggendorf Institute of Technology"
    coverpage-theme:
      title-fontfamily: "QTFuture.otf"
      title-fontsize: 30
      title-align: "center"
      title-bottom: "10.25in"
      header-fontfamily: "QTFuture.otf"
      header-bottom: "9in"
      header-width: "0.9\\textwidth"
      header-align: center
      page-html-color: "F6D5A8"
      footer-fontfamily: "QTFuture.otf"
      footer-fontsize: 15
      footer-align: "center"
      footer-bottom: "0.1\\textwidth"
      date-style: "none"
      bg-image-fading: "north"
      author-style: "plain"
      author-fontfamily: "QTFuture.otf"
      author-fontsize: 14
      author-spacing: 16
      author-fontstyle: ["textsc"]
      author-rotate: 0
      author-align: center
      author-left: "0.5\\paperwidth"
      author-bottom: "0.5\\paperheight"
      author-width: 6in
    titlepage: "none"
    titlepage-logo: "img/siegel.png"
    titlepage-footer: "Deggendorf Institute of Technology"
    titlepage-theme:
      elements: ["\\titleblock", "\\authorblock", "\\vfill", "\\logoblock", "\\footerblock"]
      page-align: "center"
      title-style: "doublelinewide"
      title-fontsize: 30
      title-fontstyle: "uppercase"
      title-space-after: "0.1\\textheight"
      subtitle-fontstyle: ["Large", "textit"]
      author-style: "plain"
      author-sep: "\\hskip1em"
      author-fontstyle: "Large"
      author-space-after: "2\\baselineskip"
      affiliation-style: "numbered-list-with-correspondence"
      affiliation-fontstyle: "large"
      affiliation-space-after: "0pt"
      footer-style: "plain"
      footer-fontstyle: ["large", "textsc"]
      footer-space-after: "0pt"
      logo-size: "0.25\\textheight"
      logo-space-after: "1cm"
    papersize: A4
    number-sections: true
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    fig-align: center
    fig-pos: 'ht'
    fig-format: pdf
    fig-width: 8
    fig-height: 5
    keep-tex: true



