project:
  type: book
  output-dir: docs

book:
  chapters:
    - index.qmd
    - chapter000_BasicConcepts.qmd
    - chapter001_Distributions.qmd
    - SamplingMethods.qmd
    - chapter002_InferentialStatistics.qmd
    - chapter003_Regression.qmd
    - chapter004_ProductionStatistics.qmd
    - chapter005_DoE.qmd
    - references.qmd
  downloads: [pdf]
    
format:
  html:
    include-in-header: mathjax.html
    theme: cosmo
    fig-width: 8
    fig-height: 5
  titlepage-pdf:
    documentclass: scrbook
    titlepage: "academic"
    titlepage-theme:
      elements: ["\\headerblock", "\\logoblock", "\\titleblock" , "\\authorblock", "\\affiliationblock", "\\vfill","\\dateblock"]
      title-space-after: "0.08\\paperheight"
      author-style: "superscript"
      author-space-between: "10pt"
      affiliation-sep: "newline"
      # author-sep: ",\ "
      # author-color: "white" 
      # author-fontfamily: "Arial"
      author-fontsize: 16
      author-spacing: 16
      author-fontstyle: ["textsc"]
      # author-align: center
      author-space-after: "0.08\\paperheight"
      affiliation-style: "numbered-list-with-correspondence"
      affiliation-fontfamily: "Arial"
      affiliation-fontsize: 16
      affiliation-spacing: 16
      # affiliation-fontstyle: ["textsc"]
      affiliation-align: left
      affiliation-space-after: "0.08\\paperheight"
    titlepage-logo: "img/siegel.png"
    titlepage-header: "Deggendorf Institute of Technology"
    papersize: A4
    number-sections: true
    toc: true
    lof: true
    lot: true
    fig-align: center
    fig-pos: 'ht'
    fig-format: pdf
    fig-width: 8
    fig-height: 5


